tasks:
  - id: "ExecContests"
    type: "cron"
    handler: "/app/Controllers/Exec/Tasks/ExecContests.php"
  - id: "BlurNewImage"
    type: "worker"
    handler: "/app/Controllers/Exec/Tasks/BlurNewImage.php"
  - id: "CompressImage"
    type: "worker"
    handler: "/app/Controllers/Exec/Tasks/CompressImage.php"